spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 12345678
#驼峰 -- 下划线命名  自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true